[env:zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200

build_flags = -DUSE_TINYUSB

lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.0
  adafruit/Adafruit TinyUSB Library
